### PR TITLE
Add new html pages

### PR DESCRIPTION
**Pull request by QueasyWhale**
# What happened?

I added three new html pages: 3x5.html, 4x6.html, and Options.html

### CODE REVIEW

**Comment by Aaron-Mann** [comment]
Hey QueasyWhale! Thanks for your contribution! Are we ready to ship this?

**Comment by QueasyWhale** [comment]
Absolutely Aaron! Go right ahead.

**Comment by Aaron-Mann** [comment]
Merged. Closing pull request.

**Comment by QueasyWhale** [comment]
# Yay! 
That was my first collaboration on Github!

**Comment by Aaron-Mann** [comment]
Cool! Merged. We have some content filling to be done on some pages. Do you want to help out with that? We especially need some extra rhetoric on the home page.

**Comment by QueasyWhale** [comment]
OK, what do you need?

**Comment by Aaron-Mann** [comment]
Additional explanation of the application, its purposes, and how to use it in the index.html. Ignore the "Web" Folder. That will be updated once the desktop client is complete.

**Pull request merged**
